[workspace]
resolver = "2"

members = ["domain", "infrastructure"]

[workspace.dependencies]
serde = { version = "1.0.216", features = ["derive"]}
sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio-rustls"]}
