[workspace]
resolver = "2"

members = ["app_server", "mission_resetter", "domain", "infrastructure"]

[workspace.dependencies]
dotenvy = "0.15.7"
serde = { version = "1.0.216", features = ["derive"]}
sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio-rustls", "chrono"]}
