services:
  nginx:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    depends_on: 
      - next_app
      - server
    networks:
      - missions_nw
  next_app:
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - 3000:3000
    networks:
      - missions_nw
  server:
    build:
      dockerfile: server.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - missions_nw
  db:
    platform: linux/amd64
    build:
      dockerfile: db.Dockerfile
      context: .
    ports:
      - "13306:3306"
    env_file:
      - mysql_config
    volumes:
      - missions_vm:/var/lib/mysql/
    networks:
      - missions_nw
volumes:
  missions_vm:
networks:
  missions_nw:
