[package]
name = "mission_resetter"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenvy ={ workspace = true }
tokio = { version = "1.42.0", features = ["full"] }
sqlx ={ workspace = true }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
